name: Test CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs: 
  build:
    strategy: 
      matrix:
        node-version: [18.x, 16.x]
    runs-on: windows-latest

    env: 
      AWS_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: AKIAZPULDDBWOU67CWW4
      AWS_SECRET_ACCESS_KEY: 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
      SENDER_EMAIL: emmanuel@cybescotech.com
      PORT: 3000

    steps: 
      - uses: actions/checkout@v2 # checkout the latest version of our code from github
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with: 
          node-version: ${{ matrix.node-version }}   
      - run: npm install
      - run: npm run test